#!/bin/sh
loader="./loader/ntl"
if test \! -x "$loader"
then
	echo "loader binary (ntl) not present"
	exit 1
fi
if test \! -d c:
then
	echo "c: not present"
	ext=extract_disk.sh
	if test -r "$ext"
	then
		. $ext
	else
		exit 2
	fi
fi

exec "$loader" $* "\\??\\c:\\winnt\\system32\\smss.exe"
