#!/bin/sh
#
# Copyright 2007-2009 (C) Mike McCormack
#
# Test launching script
# Copies a test executable onto the c: drive and runs it
#

loader="./loader/ring3k-bin"
if test \! -x "$loader"
then
	echo "loader binary (ring3k-bin) not present"
	exit 1
fi

while test "x$1" != "x"
do
	case $1 in
	-d)
		debug=1
		shift
		;;
	-t)
		trace=1
		shift
		;;
	-v)
		valgrind=1
		shift
		;;
	*)
		t="$1.exe"
		shift
		;;
	esac
done

if [ ! -d drive ]
then
	sh extract_disk.sh
fi

# copy the test into the NT directory
cp tests/$t drive/tests
ntexepath="\\??\\c:\\tests\\$t"
exec ${valgrind:+"valgrind"} "$loader" ${debug:+"-d"} ${tt:+"-s"} ${quiet:+"-q"} ${trace:+"-t"} "$ntexepath"
