#!/bin/sh
#
# Copyright 2007-2009 (C) Mike McCormack
#
# Test launching script
# Copies a test executable onto the c: drive and runs it
#

kernel="./kernel/ring3k-bin"
if test \! -x "$kernel"
then
	echo "kernel binary (ring3k-bin) not present"
	exit 1
fi

while test "x$1" != "x"
do
	case $1 in
	-d)
		debug=1
		shift
		;;
	-t)
		trace=1
		shift
		;;
	-v)
		valgrind=1
		shift
		;;
	*)
		t="$1.exe"
		shift
		;;
	esac
done

if [ ! -d drive ]
then
	sh ring3k-setup
fi

# copy the test into the NT directory
cp -f tests/win2k/ntwin32.dll drive
cp -f "tests/$t" drive/tests
ntexepath="\\??\\c:\\tests\\$t"
exec ${valgrind:+"valgrind"} "$kernel" ${debug:+"-d"} ${tt:+"-s"} ${quiet:+"-q"} ${trace:+"-t"} "$ntexepath"
