#ifndef __NTWIN32_H__
#define __NTWIN32_H__

#include "ntapi.h"

#ifndef WINXP

#define NTWIN32_THREAD_INIT_CALLBACK 74
#define NUM_USER32_CALLBACKS 90
#define NUMBER_OF_USER_SHARED_SECTIONS 29

#else

#define NTWIN32_THREAD_INIT_CALLBACK 75
#define NUM_USER32_CALLBACKS 98
#define NUMBER_OF_USER_SHARED_SECTIONS 33

#endif

#define GDI_OBJECT_DC      0x01
#define GDI_OBJECT_REGION  0x04
#define GDI_OBJECT_BITMAP  0x05
#define GDI_OBJECT_PALETTE 0x08
#define GDI_OBJECT_FONT    0x0a
#define GDI_OBJECT_BRUSH   0x10
#define GDI_OBJECT_EMF     0x21
#define GDI_OBJECT_PEN     0x30
#define GDI_OBJECT_EXTPEN  0x50

NTSTATUS NTAPI NtGdiInit(void);
HANDLE NTAPI NtGdiCreateCompatibleDC(HANDLE);
BOOLEAN NTAPI NtGdiDeleteObjectApp(HANDLE);
HANDLE NTAPI NtGdiGetStockObject(ULONG Index);
NTSTATUS NTAPI NtGdiQueryFontAssocInfo(HANDLE);

typedef struct USER_SHARED_MEMORY_INFO {
    ULONG Flags;
    PVOID Address;
} USER_SHARED_MEMORY_INFO, *PUSER_SHARED_MEMORY_INFO;

typedef struct _USER_PROCESS_CONNECT_INFO {
    ULONG Version;
    ULONG Unknown;
    ULONG MinorVersion;
    PVOID Ptr[4];
    USER_SHARED_MEMORY_INFO SharedSection[NUMBER_OF_USER_SHARED_SECTIONS];
} USER_PROCESS_CONNECT_INFO, *PUSER_PROCESS_CONNECT_INFO;

NTSTATUS NTAPI NtUserCallNoParam(ULONG);
NTSTATUS NTAPI NtUserCallOneParam(ULONG,ULONG);
NTSTATUS NTAPI NtUserCallTwoParam(ULONG,ULONG,ULONG);
HANDLE NTAPI   NtUserFindExistingCursorIcon(PUNICODE_STRING,PUNICODE_STRING,PVOID);
HANDLE NTAPI   NtUserGetDC(HANDLE);
LONG NTAPI     NtUserGetClassInfo(PVOID,PUNICODE_STRING,PVOID,PULONG,ULONG);
HANDLE NTAPI   NtUserGetThreadDesktop(ULONG,ULONG);
NTSTATUS NTAPI NtUserGetThreadState(ULONG);
NTSTATUS NTAPI NtUserInitializeClientPfnArrays(PVOID,PVOID,PVOID,PVOID);
ATOM NTAPI	   NtUserRegisterClassExWOW(PVOID,PVOID,PVOID,PVOID,ULONG,ULONG);
NTSTATUS NTAPI NtUserProcessConnect(HANDLE,PVOID,ULONG);

#endif // __NTWIN32_H__
